services:
  - type: web
    name: todo-list-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

  - type: pgsql
    name: todo-list-db
    ipAllowList: []
    plan: free
